version: "3.4"

services:
    reverse-proxy:
        image: traefik:v2.1
        container_name: reverse-proxy
        restart: "unless-stopped"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certs:/etc/ssl/certs/
            - ./traefik/:/etc/traefik/
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: host
